---
- name: 'Install java'
  homebrew_cask:
    name: java
    state: present

- name: Install Maven
  homebrew:
    name: maven
    state: present

- name: Install gradle
  homebrew:
    name: gradle
    state: present
    
 # SETUP VARIABLES ENVIRONMENT
